language: java
jdk:
    - openjdk11
install:
    - mvn -N io.takari:maven:wrapper
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: target/instapy-common*.jar
    skip_cleanup: true
